### PR TITLE
Windows compatibility

### PR DESCRIPTION
**Pull request by maxcutler**
Two changes to make the suite more compatible with Windows environments:
- Change all hard-coded "\n" instances to PHP_EOL constant.
- Allow configuration of the PHP executable path from the config file. This also helps anyone who has multiple versions of PHP installed and wants to use a non-system-default version.

### CODE REVIEW

**Comment by scribu** [comment]
> Change all hard-coded "\n" instances to PHP_EOL constant.

How come this is not a requirement for WP Core?

**Comment by maxcutler** [comment]
Core may use it for output, which is fine. It's when you try to do searches and split a file that it becomes problematic because git may auto-convert Unix line endings to Windows line endings which will cause [this](https://github.com/nb/wordpress-tests/blob/233e3d7440316c24231626f001ccb98212ecd5f4/init.php#L52) to fail.

**Comment by scribu** [comment]
But `wp-settings.php` is not part of the wp-tests repo and will always keep it's current line endings.

**Comment by maxcutler** [comment]
Not necessarily. SVN can convert line endings too, so if the WordPress folder is an SVN checkout instead of a tarball then it may have CRLF endings.

**Comment by scribu** [comment]
Anyway: http://core.trac.wordpress.org/ticket/20731

As for `echo "Installing…\n";` does that actually produce different output on a Windows console?

**Comment by maxcutler** [comment]
> ... does that actually produce different output on a Windows console?

No, it appears not. Perhaps that part was overzealous, the critical bit is the change to `$shortinit_phrase` in `init.php`.

**Comment by scribu** [comment]
About WP_PHP_BINARY, couldn't we use the same one that was used for running phpunit, i.e. PHP_BINARY?

**Comment by maxcutler** [comment]
PHP_BINARY was only added in PHP 5.4. Since WordPress still supports back to 5.2.4, we need to be able to run the test suite with older PHP versions which may not have PHP_BINARY.

**Comment by scribu** [comment]
Ok, nevermind then.

**Comment by scribu** [comment]
> Not necessarily. SVN can convert line endings too, so if the WordPress folder is an SVN checkout instead of a tarball then it may have CRLF endings.

Thinking more about this, there's simply no guarantee that PHP_EOL will match the actual line endings found in the file. That's why we should get that Core ticket fixed.

**Comment by maxcutler** [comment]
Agreed, fixing it in core or else finding a better way to handle this for unit tests would be preferable.

**Pull request merged**
