### PR TITLE
Port of GlotPress' unit test data factories.

### PR DESCRIPTION
**Pull request by maxcutler**
WordPress doesn't have a standard OO class design, so the implementation is not as clean as GP's.

This pull request is not "finished" code, but is intended to serve as a starting point for further work and discussion.

### CODE REVIEW

**Comment by scribu** [comment]
Looks like a good start. Would be nice to have an example usage in at least one of the tests.

**Comment by maxcutler** [comment]
I have many many example usages in a separate branch where I'm working on tests: https://github.com/maxcutler/wordpress-tests/tree/tests

**Comment by scribu** [comment]
Ok, merging then.

**Comment by nb** [comment]
Thanks for all the work, @maxcutler.

I haven't look at the usage of those factories for some time. If you guys have ideas for how to make them easier to use, go through use cases, this might be a good time to do it. When people start using them, it may be too late.

Also, it would be nice to have tests for the factories themselves, because they are far from trivial. I [used to have some for the GlotPress factories](http://glotpress.trac.wordpress.org/browser/trunk/t/tests_testlib) and now looking at them they are neither thorough or complete, but may be a good start.

**Pull request merged**
