### PR TITLE
Bootstrapping WordPress with early hooks.

### PR DESCRIPTION
**Pull request by kayue**
###### The Problem

As discussed in issue #16, the current wordpress-tests isn't activating plugins in the correct order; plugins should be loaded before theme is activated. 

Also, this project cannot used to test WordPress theme because it cannot switch theme when WordPress is initiating.
###### The Solution

By modifying the result returned by `wp_get_active_and_valid_plugins()` and the `TEMPLATEPATH`, `STYLESHEETPATH` constants in `wp-settings.php`, we can activate plugins and theme without touching the database. This can be done by adding filters.

In order to do this, I have made this project able to add early hooks right after the basic part of WordPress is done loading.
###### Usages

User can add early hooks in their `bootstrap.php` file.

``` php
<?php
$GLOBALS['hooks'] = array();

// Activate the Hello Dolly plugin
$GLOBALS['hooks'][] = function() {
    add_filter('option_active_plugins', function($plugins){
        $plugins[] = 'hello.php';
        return $plugins;
    });
};

// ...

require_once 'init.php';
```

A sample bootstrap file has been attached in this pull request. Please try the following command.

`phpunit --bootstrap bootstrap-with-hooks.php all`

### CODE REVIEW

**Comment by scribu** [comment]
How about instead of defining the hooks by hand, we add a higher-level global:

``` php
<?php
$GLOBALS['wp_tests_config'] = array(
  'plugins' => array( 'hello.php', 'akismet.php' ),
  'theme' => 'twentyeleven'
);
```

and then have `init.php` add the appropriate hooks.

**Comment by kayue** [comment]
Updated the `init.php` as @scribu requested. Now it takes the following config array:

```
$GLOBALS['wp_tests_config'] = array(
    'plugins'       => array('hello.php'),
    'template'      => 'twentyeleven',
    'stylesheet'    => 'twentytest',
);
```

`template` and `stylesheet` shouldn't be merged into a single variable `theme` because they repensent two different thing: parent theme and child theme.

**Comment by scribu** [comment]
Awesome! Except it should work with PHP 5.2, so the closures have to go.

**Comment by scribu** [comment]
Actually, we can make it handle arbitrary options:

``` php
<?php

function wp_tests_set_option( $value ) {
  $key = substr( current_filter(), 0, strlen( 'pre_option_' ) );

  return $GLOBALS['wp_tests_options'][$key];
}

foreach ( array_keys( $GLOBALS['wp_tests_options'] ) as $key ) {
  add_filter( 'pre_option_' . $key, 'wp_tests_set_option' );
}
```

So the config would look only slightly different:

``` php
<?php
$GLOBALS['wp_tests_options'] = array(
    'active_plugins' => array('hello.php'),
    'template' => 'twentyeleven',
    'stylesheet' => 'twentytest',
);
```

**Comment by scribu** [comment]
I was about to merge this in and continue work on it, but then I noticed this:

``` php
<?php
$wp_settings_content = file_get_contents(ABSPATH.'/wp-settings.php');
$offset = strpos($wp_settings_content, '// Load the l18n library.');
eval(substr($wp_settings_content, $offset));
```

That seems _really_ fragile. Is there no other way around it?

**Comment by kayue** [comment]
I don't see there is any other work around.

Will make the changes as you suggested.

**Comment by kayue** [comment]
BTW why `pre_option_*` instead of `option_*` ?

**Comment by scribu** [comment]
Because that's what it was designed for:

```
32  function get_option( $option, $default = false ) {
33          global $wpdb;
34  
35          // Allow plugins to short-circuit options.
36          $pre = apply_filters( 'pre_option_' . $option, false );
37          if ( false !== $pre )
38                  return $pre;
```

http://core.trac.wordpress.org/browser/trunk/wp-includes/option.php

**Comment by kayue** [comment]
Updated the code as @scribu suggested.

**Comment by scribu** [comment]
If I run `phpunit all` now, I get this:

```
PHP Fatal error:  Call to undefined function get_permalink() in /home/scribu/git/wp-tests/test_go_to.php on line 6
```

Also, some cleanup is needed:
- bootstrap-with-hooks.php is outdated
- WP_UnitTestCase::activate_tested_plugin() is obsolete

**Comment by scribu** [comment]
Note that I was using WP trunk. If I switch to 3.3.2, it works. Like I said, that `eval()` is fragile.

**Comment by scribu** [comment]
I've openened a ticket for Core, in the hopes that this becomes easier to do: http://core.trac.wordpress.org/ticket/20731

**Comment by scribu** [comment]
Perhaps instead of searching for `// Load the l18n library` we can look for `if ( SHORTINIT )` and then skip to after the next two `\n`.

**Comment by nb** [comment]
I prefer the config approach – the person setting up the tests shouldn't care how plugin activation is implemented.

@scribu, thanks for the core ticket, the `eval` is really ugly and fragile.

**Comment by kayue** [comment]
Updated as @scribu suggested.

**Comment by scribu** [comment]
Merged. Thanks, @kayue.

**Comment by scribu** [comment]
I removed test_plugin.php since it will break `phpunit all` and shouldn't be there anyway.

We should have a tutorial in the wiki instead.

_Update:_ There we go: https://github.com/nb/wordpress-tests/wiki

**Pull request merged**
